#define MESSAGE_TYPE 0
#define ALERT_MESSAGE 1
#define NAVIGATION_INFO_MESSAGE 2
#define INSTRUCTION_MESSAGE 3

#define ALERT_TYPE 10
#define ALERT_TEXT 11

#define GENERIC_ALERT 100

#define NAVIGATION_DESTINATION 20
#define NAVIGATION_DIST_TO_DEST 21
#define NAVIGATION_ETA 22

#define INSTRUCTION_TYPE 30
#define INSTRUCTION_DISTANCE 31
#define INSTRUCTION_TEXT 32

#define TURN_LEFT_INSTRUCTION 301